// Auto-generated by scripts/gen-food-image-map.mjs
// Run: node scripts/gen-food-image-map.mjs

export const RESTAURANT_IMAGE_MAP: Record<string, Record<string, string>> = {
  "Asha Tiffins": {
    "idli": "/food/asha-idli.png",
    "masala dosa": "/food/asha-masala-dosa.png"
  },
  "IDC Kitchen": {
    "idli": "/food/idc-idli.png",
    "masala dosa": "/food/idc-masala-dosa.png"
  }
}

export const FOOD_IMAGE_MAP: Record<string, string> = {
  "idli": "/food/asha-idli.png",
  "masala dosa": "/food/asha-masala-dosa.png",
  "bisi bele bath": "/food/bisi-bele-bath.png",
  "burger": "/food/burger.png",
  "cheesy dip": "/food/cheesy-dip.png",
  "coke": "/food/coke.png",
  "garlic bread": "/food/garlic-bread.png",
  "lassi": "/food/lassi.png",
  "lava cake": "/food/lava-cake.png",
  "maddur vada": "/food/maddur-vada.png",
  "margherita pizza": "/food/margherita-pizza.png",
  "namaste aloo paratha": "/food/namaste-aloo-paratha.png",
  "rice": "/food/rice.png",
  "set dosa": "/food/set-dosa.png",
  "tomato ketchup": "/food/tomato-ketchup.png",
  "veg fried rice": "/food/veg-fried-rice.png"
}

function matchesKeyword(name: string, keyword: string): boolean {
  // Match if any word from the keyword is found in the item name
  return keyword.split(" ").some((word) => name.includes(word))
}

export function getItemImage(itemName: string, restaurant: string): string | null {
  const name = itemName.toLowerCase()
  const restMap = RESTAURANT_IMAGE_MAP[restaurant]
  if (restMap) {
    for (const [keyword, image] of Object.entries(restMap)) {
      if (matchesKeyword(name, keyword)) return image
    }
  }
  for (const [keyword, image] of Object.entries(FOOD_IMAGE_MAP)) {
    if (matchesKeyword(name, keyword)) return image
  }
  return null
}

export function getFoodImage(items: { name: string }[], restaurant: string): string | null {
  for (const item of items) {
    const img = getItemImage(item.name, restaurant)
    if (img) return img
  }
  return null
}
